version: '3.7'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Africa/Johannesburg  # Set timezone to South Africa
    command: --interval 10 --http-api-metrics --http-api-token demotoken --debug